-- Create the table if it doesn't exist
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'kenya_investment_options')
BEGIN
    CREATE TABLE kenya_investment_options (
        option_id INT IDENTITY(1,1) PRIMARY KEY,
        investment_name NVARCHAR(100) NOT NULL,
        category NVARCHAR(50) NOT NULL,
        description NVARCHAR(MAX) NOT NULL,
        risk_level NVARCHAR(50) NOT NULL,
        min_investment DECIMAL(10,2) NOT NULL,
        expected_return_range NVARCHAR(20) NOT NULL,
        liquidity_rating INT NOT NULL, -- 1-5, with 5 being most liquid
        recommended_investment_horizon NVARCHAR(50) NOT NULL,
        fee_structure NVARCHAR(MAX) NOT NULL,
        tax_implications NVARCHAR(MAX) NOT NULL,
        suitable_profiles NVARCHAR(MAX) NOT NULL, -- Comma-separated profile_ids
        api_data_source NVARCHAR(255) NULL, -- API endpoint for real-time data
        data_update_frequency NVARCHAR(50) NOT NULL, -- How often data is updated
        market_data_fields NVARCHAR(MAX) NULL, -- JSON string of fields available via API
        historical_performance NVARCHAR(MAX) NULL, -- JSON string of historical performance
        volatility_score DECIMAL(5,2) NOT NULL, -- 1-10 scale
        sharpe_ratio DECIMAL(5,2) NULL, -- Risk-adjusted return metric
        auto_risk_adjustment NVARCHAR(MAX) NULL, -- JSON rules for automated risk adjustments
        created_at DATETIME DEFAULT GETDATE(),
        updated_at DATETIME DEFAULT GETDATE()
    );
END

-- Populate with comprehensive Kenya-specific investment options
INSERT INTO kenya_investment_options (
    investment_name,
    category,
    description,
    risk_level,
    min_investment,
    expected_return_range,
    liquidity_rating,
    recommended_investment_horizon,
    fee_structure,
    tax_implications,
    suitable_profiles,
    api_data_source,
    data_update_frequency,
    market_data_fields,
    historical_performance,
    volatility_score,
    sharpe_ratio,
    auto_risk_adjustment,
    created_at,
    updated_at
) VALUES 
    (
        'Nairobi Securities Exchange (NSE) Blue Chip Stocks',
        'stocks',
        'Equity investments in large, established Kenyan companies like Safaricom, EABL, and KCB that have stable earnings and regular dividend history.',
        'Moderate to High',
        3000.00,
        '8-15%',
        5,
        '5+ years',
        '{"brokerage_fee": "1.5-2% per trade", "statutory_fees": "0.12% for NSE, CMA, CDSC fees"}',
        'Dividend income taxed at 5% for residents, capital gains tax exempt for securities listed on NSE',
        'moderate,moderately_aggressive,aggressive',
        'https://api.pesaguru.com/market-data/nse/blue-chips',
        'Real-time during trading hours',
        '{"price": "Current share price", "volume": "Trading volume", "pe_ratio": "Price-to-earnings ratio", "dividend_yield": "Annual dividend percentage", "52w_high": "52-week high price", "52w_low": "52-week low price"}',
        '{"5y_avg_return": "10.2%", "max_drawdown": "18.7%", "best_year": "29.4% (2021)", "worst_year": "-8.2% (2020)"}',
        6.5,
        1.2,
        '{"market_crash": "If NSE index drops >10% in one week, increase risk level by 1", "dividend_cut": "If a stock cuts dividend, reassess its risk profile"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'NSE Growth Enterprise Market Segment (GEMS) Stocks',
        'stocks',
        'Equity investments in smaller, high-growth potential companies listed on the NSE GEMS board, offering higher returns with increased volatility.',
        'High',
        5000.00,
        '10-25%',
        3,
        '7+ years',
        '{"brokerage_fee": "1.5-2% per trade", "statutory_fees": "0.12% for NSE, CMA, CDSC fees"}',
        'Dividend income taxed at 5% for residents, capital gains tax exempt for securities listed on NSE',
        'aggressive,very_aggressive',
        'https://api.pesaguru.com/market-data/nse/gems',
        'Real-time during trading hours',
        '{"price": "Current share price", "volume": "Trading volume", "market_cap": "Market capitalization", "52w_high": "52-week high price", "52w_low": "52-week low price"}',
        '{"5y_avg_return": "14.5%", "max_drawdown": "32.3%", "best_year": "41.2% (2021)", "worst_year": "-22.7% (2020)"}',
        8.2,
        0.9,
        '{"trading_halt": "If stock is suspended from trading, flag as high risk", "rapid_growth": "If stock gains >30% in one month, reassess for volatility"}',
        GETDATE(),
        GETDATE()
    ),
    (
        '91-Day Treasury Bills',
        'bonds',
        'Short-term government securities with 91-day maturity, offering fixed interest returns with minimal risk. Interest is discounted upfront.',
        'Very Low',
        50000.00,
        '7-9%',
        4,
        '3 months',
        '{"minimum_transaction_fee": "0", "early_redemption_penalty": "Loss of interest"}',
        'Interest income is subject to withholding tax at 15% for residents',
        'ultra_conservative,conservative',
        'https://api.pesaguru.com/market-data/cbk/t-bills/91',
        'Weekly updates after CBK auctions',
        '{"yield": "Current annualized yield", "last_auction_date": "Date of last auction", "next_auction_date": "Date of next auction", "amount_offered": "Amount offered in latest auction"}',
        '{"5y_avg_yield": "8.1%", "max_yield": "11.2% (2019)", "min_yield": "6.9% (2022)"}',
        1.2,
        2.1,
        '{"yield_spike": "If yields spike >2% in one auction, reassess risk due to market instability", "inflation": "If inflation exceeds t-bill yield, flag negative real returns"}',
        GETDATE(),
        GETDATE()
    ),
    (
        '182-Day Treasury Bills',
        'bonds',
        'Short-term government securities with 182-day maturity, offering fixed interest returns with minimal risk. Interest is discounted upfront.',
        'Very Low',
        50000.00,
        '8-10%',
        3,
        '6 months',
        '{"minimum_transaction_fee": "0", "early_redemption_penalty": "Loss of interest"}',
        'Interest income is subject to withholding tax at 15% for residents',
        'ultra_conservative,conservative',
        'https://api.pesaguru.com/market-data/cbk/t-bills/182',
        'Weekly updates after CBK auctions',
        '{"yield": "Current annualized yield", "last_auction_date": "Date of last auction", "next_auction_date": "Date of next auction", "amount_offered": "Amount offered in latest auction"}',
        '{"5y_avg_yield": "8.9%", "max_yield": "11.9% (2019)", "min_yield": "7.4% (2022)"}',
        1.4,
        2.2,
        '{"yield_spike": "If yields spike >2% in one auction, reassess risk due to market instability", "inflation": "If inflation exceeds t-bill yield, flag negative real returns"}',
        GETDATE(),
        GETDATE()
    ),
    (
        '364-Day Treasury Bills',
        'bonds',
        'Short-term government securities with 364-day maturity, offering fixed interest returns with minimal risk. Interest is discounted upfront.',
        'Low',
        50000.00,
        '9-11%',
        3,
        '1 year',
        '{"minimum_transaction_fee": "0", "early_redemption_penalty": "Loss of interest"}',
        'Interest income is subject to withholding tax at 15% for residents',
        'ultra_conservative,conservative,moderately_conservative',
        'https://api.pesaguru.com/market-data/cbk/t-bills/364',
        'Weekly updates after CBK auctions',
        '{"yield": "Current annualized yield", "last_auction_date": "Date of last auction", "next_auction_date": "Date of next auction", "amount_offered": "Amount offered in latest auction"}',
        '{"5y_avg_yield": "9.7%", "max_yield": "12.5% (2019)", "min_yield": "8.1% (2022)"}',
        1.7,
        2.3,
        '{"yield_spike": "If yields spike >2% in one auction, reassess risk due to market instability", "inflation": "If inflation exceeds t-bill yield, flag negative real returns"}',
        GETDATE(),
        GETDATE()
    ),
    (
        '2-Year Treasury Bonds',
        'bonds',
        'Medium-term government securities with 2-year maturity, providing regular coupon payments every 6 months and principal at maturity.',
        'Low',
        50000.00,
        '10-12%',
        2,
        '2 years',
        '{"minimum_transaction_fee": "0", "secondary_market_fees": "0.05% of value when traded on secondary market"}',
        'Interest income is subject to withholding tax at 15% for residents',
        'conservative,moderately_conservative',
        'https://api.pesaguru.com/market-data/cbk/bonds/2year',
        'Monthly updates',
        '{"yield": "Current yield rate", "coupon_rate": "Fixed interest rate", "next_auction_date": "Date of next auction", "secondary_market_price": "Current price on secondary market"}',
        '{"5y_avg_yield": "10.5%", "max_yield": "13.2% (2019)", "min_yield": "9.1% (2022)"}',
        2.1,
        2.0,
        '{"yield_curve_inversion": "If 2y bonds yield more than 5y bonds, flag economic recession risk", "secondary_premium": "If trading at >5% premium on secondary market, flag as potentially overvalued"}',
        GETDATE(),
        GETDATE()
    ),
    (
        '5-Year Treasury Bonds',
        'bonds',
        'Medium-term government securities with 5-year maturity, providing regular coupon payments every 6 months and principal at maturity.',
        'Low to Moderate',
        50000.00,
        '11-13%',
        2,
        '5 years',
        '{"minimum_transaction_fee": "0", "secondary_market_fees": "0.05% of value when traded on secondary market"}',
        'Interest income is subject to withholding tax at 15% for residents',
        'conservative,moderately_conservative,moderate',
        'https://api.pesaguru.com/market-data/cbk/bonds/5year',
        'Monthly updates',
        '{"yield": "Current yield rate", "coupon_rate": "Fixed interest rate", "next_auction_date": "Date of next auction", "secondary_market_price": "Current price on secondary market"}',
        '{"5y_avg_yield": "11.8%", "max_yield": "14.7% (2019)", "min_yield": "10.1% (2022)"}',
        3.2,
        1.8,
        '{"yield_spread_widening": "If spread between 5y and 91d yields widens >3%, flag increased economic uncertainty", "inflation_trend": "If inflation trend exceeds bond yield, reassess real returns"}',
        GETDATE(),
        GETDATE()
    ),
    (
        '10-Year Treasury Bonds',
        'bonds',
        'Long-term government securities with 10-year maturity, providing regular coupon payments every 6 months and principal at maturity.',
        'Moderate',
        50000.00,
        '12-14%',
        1,
        '10 years',
        '{"minimum_transaction_fee": "0", "secondary_market_fees": "0.05% of value when traded on secondary market"}',
        'Interest income is subject to withholding tax at 15% for residents',
        'moderate,moderately_aggressive',
        'https://api.pesaguru.com/market-data/cbk/bonds/10year',
        'Monthly updates',
        '{"yield": "Current yield rate", "coupon_rate": "Fixed interest rate", "next_auction_date": "Date of next auction", "secondary_market_price": "Current price on secondary market"}',
        '{"5y_avg_yield": "12.9%", "max_yield": "16.3% (2019)", "min_yield": "11.2% (2022)"}',
        4.1,
        1.6,
        '{"interest_rate_risk": "If central bank raises rates >1.5% within 6 months, flag heightened interest rate risk", "duration_sensitivity": "High sensitivity to interest rate changes due to long duration"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'Infrastructure Bonds',
        'bonds',
        'Long-term government bonds specifically issued to fund infrastructure projects, offering tax advantages as interest income is tax-exempt.',
        'Low to Moderate',
        50000.00,
        '11-14%',
        1,
        '7-25 years',
        '{"minimum_transaction_fee": "0", "secondary_market_fees": "0.05% of value when traded on secondary market"}',
        'Interest income is TAX-FREE for Kenyan residents, making effective returns higher than standard bonds',
        'conservative,moderately_conservative,moderate',
        'https://api.pesaguru.com/market-data/cbk/bonds/infrastructure',
        'Monthly updates',
        '{"yield": "Current yield rate", "coupon_rate": "Fixed interest rate", "next_auction_date": "Date of next auction", "secondary_market_price": "Current price on secondary market", "tax_equivalent_yield": "Equivalent yield when considering tax advantage"}',
        '{"5y_avg_yield": "12.2%", "max_yield": "15.1% (2019)", "min_yield": "10.7% (2022)"}',
        3.5,
        1.9,
        '{"oversubscription": "If bond is oversubscribed by >200%, flag potential yield compression", "illiquidity_risk": "If secondary market trading volume drops >50%, flag potential liquidity issues"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'CIC Money Market Fund',
        'mutual_funds',
        'Low-risk fund investing in short-term money market instruments like T-bills, fixed deposits, and commercial paper to preserve capital while providing income.',
        'Very Low',
        5000.00,
        '8-10%',
        5,
        '0-1 years',
        '{"management_fee": "2-3% per annum", "exit_fee": "0-2% for redemptions within certain period"}',
        'Interest income is subject to withholding tax at 15% for residents',
        'ultra_conservative,conservative',
        'https://api.pesaguru.com/market-data/funds/cic-money-market',
        'Daily updates',
        '{"current_yield": "Annualized current yield", "nav": "Net Asset Value per unit", "fund_size": "Total fund size in KES", "asset_allocation": "Breakdown of fund investments"}',
        '{"5y_avg_return": "9.2%", "max_return": "10.7% (2019)", "min_return": "8.1% (2022)"}',
        1.1,
        2.4,
        '{"yield_trending_down": "If yield drops for 3 consecutive months, reassess fund management", "liquidity_position": "If fund cash position drops below 15%, flag potential liquidity issues"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'Sanlam Money Market Fund',
        'mutual_funds',
        'Low-risk fund investing in short-term money market instruments to provide stable returns with high liquidity and capital preservation.',
        'Very Low',
        2500.00,
        '8-10%',
        5,
        '0-1 years',
        '{"management_fee": "2-2.5% per annum", "exit_fee": "0% after 30 days"}',
        'Interest income is subject to withholding tax at 15% for residents',
        'ultra_conservative,conservative',
        'https://api.pesaguru.com/market-data/funds/sanlam-money-market',
        'Daily updates',
        '{"current_yield": "Annualized current yield", "nav": "Net Asset Value per unit", "fund_size": "Total fund size in KES", "asset_allocation": "Breakdown of fund investments"}',
        '{"5y_avg_return": "9.0%", "max_return": "10.5% (2019)", "min_return": "7.9% (2022)"}',
        1.0,
        2.5,
        '{"credit_quality_decline": "If average credit quality of holdings decreases, increase risk level", "sector_concentration": "If >25% in single sector, flag concentration risk"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'CIC Balanced Fund',
        'mutual_funds',
        'Moderate-risk fund investing in both equities and fixed income securities to balance growth potential with income generation.',
        'Moderate',
        5000.00,
        '9-12%',
        4,
        '3-5 years',
        '{"management_fee": "3-4% per annum", "exit_fee": "1-2% for redemptions within certain period"}',
        'Dividend and interest income subject to respective taxes; capital gains within fund not taxed',
        'moderate,moderately_conservative',
        'https://api.pesaguru.com/market-data/funds/cic-balanced',
        'Daily updates',
        '{"current_yield": "Annualized current yield", "nav": "Net Asset Value per unit", "fund_size": "Total fund size in KES", "asset_allocation": "Breakdown between equities and fixed income"}',
        '{"5y_avg_return": "10.5%", "max_return": "15.2% (2021)", "min_return": "3.1% (2020)"}',
        4.2,
        1.5,
        '{"equity_correlation": "If fund correlation with NSE index exceeds 0.8, flag increased market risk", "allocation_drift": "If equity allocation drifts >10% from target, flag potential style drift"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'Britam Equity Fund',
        'mutual_funds',
        'High-risk fund primarily investing in Kenyan equities listed on the NSE, focusing on long-term capital appreciation.',
        'High',
        1000.00,
        '10-15%',
        4,
        '5+ years',
        '{"management_fee": "3-5% per annum", "performance_fee": "0-20% of returns above benchmark", "exit_fee": "1-2% for redemptions within certain period"}',
        'Dividend income taxed at 5% for residents; capital gains within fund not taxed',
        'moderately_aggressive,aggressive',
        'https://api.pesaguru.com/market-data/funds/britam-equity',
        'Daily updates',
        '{"current_return": "Year-to-date return", "nav": "Net Asset Value per unit", "fund_size": "Total fund size in KES", "sector_allocation": "Breakdown of sector exposures", "top_holdings": "Top 10 stock holdings"}',
        '{"5y_avg_return": "11.2%", "max_return": "31.5% (2021)", "min_return": "-12.3% (2020)"}',
        7.1,
        0.8,
        '{"sector_overweight": "If fund allocates >30% to single sector, flag concentration risk", "cash_buildup": "If cash position exceeds 15% for >3 months, flag potential market timing concerns"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'ILAM Fahari I-REIT',
        'real_estate',
        'Kenya''s first REIT (Real Estate Investment Trust) investing in income-generating commercial properties, offering both rental income and potential capital appreciation.',
        'Moderate',
        10000.00,
        '8-12%',
        3,
        '5+ years',
        '{"management_fee": "0.5-1.5% of net asset value", "property_management_fee": "1-3% of gross rental income"}',
        'REIT dividend distributions taxed at resident withholding tax rate of 5%',
        'moderately_conservative,moderate,moderately_aggressive',
        'https://api.pesaguru.com/market-data/reits/ilam-fahari',
        'Daily share price; quarterly property valuations',
        '{"share_price": "Current trading price on NSE", "nav_per_unit": "Net Asset Value per unit", "distribution_yield": "Annual distribution as percentage of price", "vacancy_rate": "Current vacancy rate across properties", "property_value": "Total value of property portfolio"}',
        '{"5y_avg_return": "8.7%", "max_return": "13.2% (2018)", "min_return": "4.1% (2020)"}',
        4.8,
        1.1,
        '{"property_concentration": "If single property exceeds 40% of portfolio, flag concentration risk", "vacancy_trend": "If vacancy rate increases for 2 consecutive quarters, reassess income stability"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'NCBA SACCO Shares',
        'fixed_deposits',
        'Savings and Credit Cooperative shares offering annual dividends based on the SACCO''s performance, typically higher than traditional bank deposits.',
        'Low',
        10000.00,
        '7-12%',
        2,
        '3+ years',
        '{"membership_fee": "One-time KES 1,000-5,000", "annual_fee": "KES 0-1,000"}',
        'Dividend income from SACCOs is exempt from withholding tax',
        'conservative,moderately_conservative',
        'https://api.pesaguru.com/market-data/saccos/ncba',
        'Annual updates with quarterly estimates',
        '{"latest_dividend_rate": "Most recent annual dividend rate", "projected_dividend": "Projected rate for current year", "savings_interest_rate": "Current interest on deposits", "loan_interest_rate": "Current lending rate to members"}',
        '{"5y_avg_dividend": "9.5%", "max_dividend": "12.7% (2019)", "min_dividend": "7.2% (2020)"}',
        2.5,
        1.8,
        '{"loan_default_increase": "If loan defaults rise >5% in one quarter, flag dividend risk", "deposit_withdrawal_trend": "If net withdrawals exceed 10% of deposits, flag liquidity concerns"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'Stima SACCO Shares',
        'fixed_deposits',
        'Shares in one of Kenya''s largest energy sector SACCOs, known for consistent dividend payouts and member benefits.',
        'Low',
        5000.00,
        '8-13%',
        2,
        '3+ years',
        '{"membership_fee": "One-time KES 1,000-3,000", "annual_fee": "KES 0-500"}',
        'Dividend income from SACCOs is exempt from withholding tax',
        'conservative,moderately_conservative',
        'https://api.pesaguru.com/market-data/saccos/stima',
        'Annual updates with quarterly estimates',
        '{"latest_dividend_rate": "Most recent annual dividend rate", "projected_dividend": "Projected rate for current year", "savings_interest_rate": "Current interest on deposits", "loan_interest_rate": "Current lending rate to members"}',
        '{"5y_avg_dividend": "10.2%", "max_dividend": "14.1% (2019)", "min_dividend": "7.8% (2020)"}',
        2.7,
        1.9,
        '{"membership_growth": "If membership growth turns negative for 2 consecutive quarters, flag retention issues", "asset_quality_decline": "If non-performing loans exceed 12%, flag increased default risk"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'Equity Fixed Deposit',
        'fixed_deposits',
        'Term deposits with Equity Bank offering fixed interest rates for specified periods, ideal for capital preservation with predictable returns.',
        'Very Low',
        100000.00,
        '6-8%',
        1,
        '3 months - 5 years',
        '{"early_withdrawal_penalty": "Forfeiture of interest or penalty fees", "minimum_balance_fee": "0"}',
        'Interest income is subject to withholding tax at 15% for residents',
        'ultra_conservative,conservative',
        'https://api.pesaguru.com/market-data/fixed-deposits/equity',
        'Weekly updates',
        '{"current_rates": "Current interest rates by term length", "minimum_deposit": "Minimum deposit requirement", "special_offers": "Any promotional rates available"}',
        '{"5y_avg_rate": "7.1%", "max_rate": "9.0% (2019)", "min_rate": "5.5% (2022)"}',
        0.8,
        2.7,
        '{"bank_downgrade": "If bank credit rating is downgraded, reassess counterparty risk", "rate_comparison": "If rate falls >2% below market average, flag potential competitiveness issues"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'KCB Fixed Deposit',
        'fixed_deposits',
        'Term deposits with KCB Bank offering fixed interest rates for specified periods, ideal for capital preservation with predictable returns.',
        'Very Low',
        100000.00,
        '6-8%',
        1,
        '3 months - 5 years',
        '{"early_withdrawal_penalty": "Forfeiture of interest or penalty fees", "minimum_balance_fee": "0"}',
        'Interest income is subject to withholding tax at 15% for residents',
        'ultra_conservative,conservative',
        'https://api.pesaguru.com/market-data/fixed-deposits/kcb',
        'Weekly updates',
        '{"current_rates": "Current interest rates by term length", "minimum_deposit": "Minimum deposit requirement", "special_offers": "Any promotional rates available"}',
        '{"5y_avg_rate": "7.0%", "max_rate": "8.8% (2019)", "min_rate": "5.3% (2022)"}',
        0.7,
        2.8,
        '{"bank_downgrade": "If bank credit rating is downgraded, reassess counterparty risk", "rate_comparison": "If rate falls >2% below market average, flag potential competitiveness issues"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'M-Shwari Savings',
        'fixed_deposits',
        'Mobile-based savings account offered through M-Pesa and NCBA, providing interest on deposits with easy access via mobile phone.',
        'Very Low',
        1.00,
        '5-7%',
        4,
        '0-1 years',
        '{"account_maintenance_fee": "0", "withdrawal_fee": "0"}',
        'Interest income is subject to withholding tax at 15% for residents',
        'ultra_conservative,conservative',
        'https://api.pesaguru.com/market-data/mobile-savings/m-shwari',
        'Monthly updates',
        '{"current_rate": "Current annualized interest rate", "lock_savings_rate": "Rate for fixed-term savings", "loan_rate": "Current Fuliza overdraft rate"}',
        '{"5y_avg_rate": "6.0%", "max_rate": "7.5% (2018)", "min_rate": "5.0% (2023)"}',
        0.5,
        3.0,
        '{"platform_downtime": "If service availability drops below 98%, flag operational risk", "rate_trend": "If rate remains unchanged for >18 months, flag potential yield compression"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'KCB M-Pesa Account',
        'fixed_deposits',
        'Mobile-based savings account offered through M-Pesa and KCB, providing interest on deposits with easy access via mobile phone.',
        'Very Low',
        1.00,
        '5-7%',
        4,
        '0-1 years',
        '{"account_maintenance_fee": "0", "withdrawal_fee": "0"}',
        'Interest income is subject to withholding tax at 15% for residents',
        'ultra_conservative,conservative',
        'https://api.pesaguru.com/market-data/mobile-savings/kcb-mpesa',
        'Monthly updates',
        '{"current_rate": "Current annualized interest rate", "lock_savings_rate": "Rate for fixed-term savings", "loan_rate": "Current overdraft rate"}',
        '{"5y_avg_rate": "5.8%", "max_rate": "7.3% (2018)", "min_rate": "4.8% (2023)"}',
        0.5,
        3.0,
        '{"platform_downtime": "If service availability drops below 98%, flag operational risk", "rate_trend": "If rate remains unchanged for >18 months, flag potential yield compression"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'Cytonn High Yield Solutions',
        'alternative_investments',
        'High-yield real estate-backed investment product offering significantly higher returns than traditional investments, but with increased risk.',
        'Very High',
        100000.00,
        '14-18%',
        1,
        '3-5 years',
        '{"management_fee": "2-3% per annum", "early_redemption_fee": "15-25% of capital"}',
        'Interest income taxable as ordinary income',
        'aggressive,very_aggressive',
        'https://api.pesaguru.com/market-data/alternative/cytonn',
        'Quarterly updates',
        '{"current_yield": "Current advertised yield", "portfolio_status": "Status of real estate projects", "capital_raising": "Current capital raising status"}',
        '{"5y_avg_return": "15.2%", "max_return": "18.0% (2018)", "min_return": "12.5% (2021)"}',
        8.5,
        0.7,
        '{"project_delays": "If project completion exceeds timeline by >6 months, escalate risk rating", "regulatory_scrutiny": "If regulatory warnings issued, flag immediate risk alert"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'Greenhouse Agribusiness Investment',
        'alternative_investments',
        'Agricultural investment in greenhouse farming, offering returns from crop sales with operational management handled by specialized firms.',
        'High',
        150000.00,
        '12-20%',
        1,
        '2-5 years',
        '{"setup_fee": "5-10% of investment", "management_fee": "Typically 20-30% of harvest proceeds"}',
        'Income taxable as business income at personal income tax rates',
        'aggressive,very_aggressive',
        'https://api.pesaguru.com/market-data/alternative/greenhouse',
        'Seasonal updates (quarterly)',
        '{"crop_cycle_status": "Current phase of crop production", "market_prices": "Current market prices for produce", "expected_harvest_date": "Next projected harvest date", "historical_yields": "Previous harvest yields"}',
        '{"5y_avg_return": "14.5%", "max_return": "24.0% (harvest with premium prices)", "min_return": "6.0% (poor harvest season)"}',
        7.8,
        0.8,
        '{"weather_event": "If adverse weather affects >30% of region, flag crop risk", "disease_outbreak": "If plant disease detected in region, escalate risk level", "market_price_drop": "If crop prices fall >20% below projection, flag revenue risk"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'Bitcoin via Local Exchanges',
        'cryptocurrency',
        'Bitcoin purchased through Kenyan P2P exchanges or platforms that support M-Pesa, offering high-risk, high-reward potential with significant volatility.',
        'Very High',
        1000.00,
        '-20-100%',
        4,
        '3-7 years',
        '{"exchange_fee": "1-3% per transaction", "network_fee": "Variable depending on network congestion", "withdrawal_fee": "Flat fee or percentage for fiat conversion"}',
        'Cryptocurrency gains not explicitly addressed in Kenyan tax code; potentially taxable as capital gains',
        'very_aggressive',
        'https://api.pesaguru.com/market-data/crypto/bitcoin',
        'Real-time updates',
        '{"price_usd": "Current BTC/USD price", "price_kes": "Current BTC/KES price", "24h_change": "24-hour price change percentage", "trading_volume": "24-hour trading volume", "market_cap": "Total market capitalization", "dominance": "BTC dominance in crypto market"}',
        '{"5y_avg_return": "40.2%", "max_return": "302.8% (2020-2021)", "min_return": "-72.6% (2022)"}',
        9.7,
        0.5,
        '{"volatility_spike": "If 30-day volatility exceeds 100%, flag extreme risk", "regulatory_action": "If CBK issues new restrictions, flag regulatory risk", "exchange_issues": "If local exchanges face withdrawal problems, flag counterparty risk"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'Ethereum via Local Exchanges',
        'cryptocurrency',
        'Ethereum purchased through Kenyan P2P exchanges or platforms that support M-Pesa, offering high-risk, high-reward potential with significant volatility.',
        'Very High',
        1000.00,
        '-30-120%',
        4,
        '3-7 years',
        '{"exchange_fee": "1-3% per transaction", "network_fee": "Variable depending on network congestion", "withdrawal_fee": "Flat fee or percentage for fiat conversion"}',
        'Cryptocurrency gains not explicitly addressed in Kenyan tax code; potentially taxable as capital gains',
        'very_aggressive',
        'https://api.pesaguru.com/market-data/crypto/ethereum',
        'Real-time updates',
        '{"price_usd": "Current ETH/USD price", "price_kes": "Current ETH/KES price", "24h_change": "24-hour price change percentage", "trading_volume": "24-hour trading volume", "market_cap": "Total market capitalization", "gas_fees": "Current network transaction costs"}',
        '{"5y_avg_return": "52.1%", "max_return": "456.2% (2020-2021)", "min_return": "-80.5% (2022)"}',
        9.9,
        0.4,
        '{"smart_contract_risk": "If major protocols built on Ethereum face security issues, flag technical risk", "merge_related_events": "If network upgrades scheduled, monitor for technical risks", "regulatory_action": "If CBK issues new restrictions, flag regulatory risk"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'NewGold ETF',
        'etf',
        'Exchange-traded fund listed on the NSE that tracks the price of gold, providing exposure to gold price movements without physical ownership.',
        'Moderate',
        5000.00,
        '5-10%',
        5,
        '3-7 years',
        '{"management_fee": "0.4-0.8% per annum", "brokerage_fee": "1-2% per trade"}',
        'Dividend distributions (if any) subject to 5% withholding tax for NSE-listed securities',
        'moderate,moderately_aggressive,aggressive,very_aggressive',
        'https://api.pesaguru.com/market-data/etf/newgold',
        'Real-time during trading hours',
        '{"price": "Current share price on NSE", "nav": "Net Asset Value per unit", "premium_discount": "Trading premium/discount to NAV", "gold_price_usd": "Current gold price in USD", "gold_price_kes": "Current gold price in KES"}',
        '{"5y_avg_return": "7.2%", "max_return": "24.5% (2020)", "min_return": "-10.2% (2022)"}',
        5.3,
        0.9,
        '{"dollar_strength": "If USD/KES rate strengthens significantly, monitor gold price in KES", "tracking_error": "If ETF performance deviates >3% from gold price, flag tracking risk", "liquidity_risk": "If trading volume drops >50% below average, flag potential liquidity issues"}',
        GETDATE(),
        GETDATE()
    ),
    (
        'Corporate Bonds (Safaricom, EABL)',
        'bonds',
        'Debt securities issued by major Kenyan corporations offering fixed interest payments, typically higher than government securities with moderate risk.',
        'Low to Moderate',
        100000.00,
        '11-14%',
        3,
        '3-10 years',
        '{"placement_fee": "0-1%", "secondary_market_fees": "0.05-0.1% when traded"}',
        'Interest income subject to 15% withholding tax for residents',
        'conservative,moderately_conservative,moderate',
        'https://api.pesaguru.com/market-data/corporate-bonds',
        'Daily updates for traded bonds',
        '{"yield": "Current yield to maturity", "price": "Current trading price (% of par)", "credit_rating": "Current credit rating", "trading_volume": "Recent trading activity", "maturity_date": "Date of principal repayment"}',
        '{"5y_avg_yield": "12.5%", "max_yield": "15.2% (2019)", "min_yield": "10.8% (2022)"}',
        3.8,
        1.6,
        '{"credit_rating_change": "If issuer credit rating changes, reassess risk profile", "yield_spread_widening": "If spread over government bonds widens >3%, flag credit concern", "trading_illiquidity": "If no trades reported for >30 days, flag liquidity risk"}',
        GETDATE(),
        GETDATE()
    );

-- Create indexes for faster lookups
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_kenya_options_category' AND object_id = OBJECT_ID('kenya_investment_options'))
BEGIN
    CREATE INDEX idx_kenya_options_category ON kenya_investment_options(category);
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_kenya_options_risk' AND object_id = OBJECT_ID('kenya_investment_options'))
BEGIN
    CREATE INDEX idx_kenya_options_risk ON kenya_investment_options(risk_level);
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'idx_kenya_options_min_investment' AND object_id = OBJECT_ID('kenya_investment_options'))
BEGIN
    CREATE INDEX idx_kenya_options_min_investment ON kenya_investment_options(min_investment);
END

-- Create views for simplified API access
IF EXISTS (SELECT * FROM sys.views WHERE name = 'v_kenya_investment_options_summary')
BEGIN
    DROP VIEW v_kenya_investment_options_summary;
END

GO

CREATE VIEW v_kenya_investment_options_summary AS
SELECT 
    option_id,
    investment_name,
    category,
    risk_level,
    min_investment,
    expected_return_range,
    liquidity_rating,
    recommended_investment_horizon,
    suitable_profiles
FROM 
    kenya_investment_options;

GO

-- Create view for risk analysis
IF EXISTS (SELECT * FROM sys.views WHERE name = 'v_kenya_investments_by_risk')
BEGIN
    DROP VIEW v_kenya_investments_by_risk;
END

GO

CREATE VIEW v_kenya_investments_by_risk AS
SELECT 
    risk_level,
    COUNT(*) as option_count,
    AVG(volatility_score) as avg_volatility,
    AVG(CAST(SUBSTRING(SUBSTRING(expected_return_range, 0, CHARINDEX('-', expected_return_range)), 
        PATINDEX('%[0-9]%', SUBSTRING(expected_return_range, 0, CHARINDEX('-', expected_return_range))), 
        LEN(SUBSTRING(expected_return_range, 0, CHARINDEX('-', expected_return_range)))) AS DECIMAL(5,2))) as min_return,
    AVG(CAST(SUBSTRING(SUBSTRING(expected_return_range, CHARINDEX('-', expected_return_range) + 1, LEN(expected_return_range)), 
        PATINDEX('%[0-9]%', SUBSTRING(expected_return_range, CHARINDEX('-', expected_return_range) + 1, LEN(expected_return_range))), 
        LEN(SUBSTRING(expected_return_range, CHARINDEX('-', expected_return_range) + 1, LEN(expected_return_range))) - 
        CHARINDEX('%', SUBSTRING(expected_return_range, CHARINDEX('-', expected_return_range) + 1, LEN(expected_return_range)))) AS DECIMAL(5,2))) as max_return,
    AVG(sharpe_ratio) as avg_sharpe_ratio
FROM 
    kenya_investment_options
GROUP BY 
    risk_level
ORDER BY 
    CASE 
        WHEN risk_level = 'Very Low' THEN 1
        WHEN risk_level = 'Low' THEN 2
        WHEN risk_level = 'Low to Moderate' THEN 3
        WHEN risk_level = 'Moderate' THEN 4
        WHEN risk_level = 'Moderate to High' THEN 5
        WHEN risk_level = 'High' THEN 6
        WHEN risk_level = 'Very High' THEN 7
        ELSE 8
    END;