apiVersion: apps/v1
kind: Deployment
metadata:
  name: pesaguru-api
  namespace: pesaguru
  labels:
    app: pesaguru
    component: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pesaguru
      component: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pesaguru
        component: api
    spec:
      containers:
      - name: api-server
        image: pesaguru/api-server:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 9000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: API_PORT
          value: "9000"
        - name: CORS_ORIGIN
          value: "https://pesaguru.co.ke,https://app.pesaguru.co.ke"
        - name: AI_SERVICE_URL
          value: "http://pesaguru-ai:8000"
        - name: RATE_LIMIT_WINDOW_MS
          value: "60000"
        - name: RATE_LIMIT_MAX_REQUESTS
          value: "100"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: pesaguru-api-secrets
              key: jwt-secret
        - name: JWT_EXPIRES_IN
          value: "8h"
        - name: REDIS_HOST
          value: "pesaguru-redis"
        - name: REDIS_PORT
          value: "6379"
        - name: DB_HOST
          value: "pesaguru-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "pesaguru"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pesaguru-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pesaguru-db-credentials
              key: password
        - name: NSE_API_KEY
          valueFrom:
            secretKeyRef:
              name: pesaguru-api-keys
              key: nse-api-key
        - name: MPESA_API_KEY
          valueFrom:
            secretKeyRef:
              name: pesaguru-api-keys
              key: mpesa-api-key
        - name: MPESA_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: pesaguru-api-keys
              key: mpesa-consumer-key
        - name: MPESA_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              name: pesaguru-api-keys
              key: mpesa-consumer-secret
        - name: MPESA_SHORTCODE
          valueFrom:
            secretKeyRef:
              name: pesaguru-api-keys
              key: mpesa-shortcode
        - name: MPESA_PASSKEY
          valueFrom:
            secretKeyRef:
              name: pesaguru-api-keys
              key: mpesa-passkey
        volumeMounts:
        - name: api-cache
          mountPath: /app/cache
        - name: api-temp
          mountPath: /app/temp
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
      volumes:
      - name: api-cache
        emptyDir: {}
      - name: api-temp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pesaguru-api
  namespace: pesaguru
  labels:
    app: pesaguru
    component: api
spec:
  selector:
    app: pesaguru
    component: api
  ports:
  - port: 80
    targetPort: http
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pesaguru-api-hpa
  namespace: pesaguru
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pesaguru-api
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 5
        periodSeconds: 30
      selectPolicy: Max
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pesaguru-api-ingress
  namespace: pesaguru
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.pesaguru.co.ke
    secretName: pesaguru-api-tls
  rules:
  - host: api.pesaguru.co.ke
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pesaguru-api
            port:
              name: http
