apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pesaguru-ingress
  namespace: pesaguru
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # TLS and security configurations
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    
    # Security headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-XSS-Protection: 1; mode=block";
      more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
      more_set_headers "Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; img-src 'self' data:; font-src 'self' https://cdnjs.cloudflare.com; connect-src 'self' https://api.pesaguru.co.ke;";
    
    # Performance optimizations
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    
    # CORS settings
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    
    # Rate limiting
    nginx.ingress.kubernetes.io/limit-connections: "100"
    nginx.ingress.kubernetes.io/limit-rps: "50"
    nginx.ingress.kubernetes.io/limit-rpm: "1000"
spec:
  tls:
  - hosts:
    - pesaguru.co.ke
    - www.pesaguru.co.ke
    secretName: pesaguru-web-tls
  - hosts:
    - api.pesaguru.co.ke
    secretName: pesaguru-api-tls
  - hosts:
    - admin.pesaguru.co.ke
    secretName: pesaguru-admin-tls
  rules:
  # Main website
  - host: pesaguru.co.ke
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pesaguru-web
            port:
              number: 80
  - host: www.pesaguru.co.ke
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pesaguru-web
            port:
              number: 80
  
  # API service
  - host: api.pesaguru.co.ke
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pesaguru-api
            port:
              number: 80
              
  # Admin portal
  - host: admin.pesaguru.co.ke
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pesaguru-admin
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pesaguru-chatbot-ingress
  namespace: pesaguru
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # WebSocket support for chatbot
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "pesaguru-chatbot"
    
    # TLS configuration
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    
    # Security headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-XSS-Protection: 1; mode=block";
      more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
    
    # CORS settings
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
spec:
  tls:
  - hosts:
    - chat.pesaguru.co.ke
    secretName: pesaguru-chat-tls
  rules:
  - host: chat.pesaguru.co.ke
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pesaguru-chatbot
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pesaguru-redirect-ingress
  namespace: pesaguru
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://pesaguru.co.ke"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - app.pesaguru.co.ke
    secretName: pesaguru-app-redirect-tls
  rules:
  - host: app.pesaguru.co.ke
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pesaguru-web
            port:
              number: 80
